#!/usr/bin/env python3
"""
Compare Coq and Rust golden vectors for bounded PO-8 evidence.

This script compares JSON generated from the Coq-extracted witness serializer
against JSON generated from the Rust implementation. The current Coq varint
model covers compact-size values through the 0xFD/u16 range.

Usage:
    python3 compare_vectors.py
"""

import json
import sys


def main():
    """Compare Coq and Rust golden vectors."""
    # Load Coq vectors
    try:
        with open("formal/coq/extraction/coq_vectors.json", "r") as f:
            coq_data = json.load(f)
    except FileNotFoundError:
        print("ERROR: Coq vectors not found at formal/coq/extraction/coq_vectors.json")
        print("Run './build_extraction.sh' first to generate the vectors.")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in Coq vectors: {e}")
        sys.exit(1)

    # Load Rust vectors
    try:
        with open("rust_vectors.json", "r") as f:
            rust_data = json.load(f)
    except FileNotFoundError:
        print("ERROR: Rust vectors not found at rust_vectors.json")
        print(
            "Run 'cargo run --example generate_golden_vectors > rust_vectors.json' first."
        )
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in Rust vectors: {e}")
        sys.exit(1)

    # Load optional exhaustive varint / witness / sighash refinement summaries when
    # generated by build_extraction.sh. Keeping this optional preserves hermetic
    # local vector comparison for the checked-in baseline.
    coq_varint = None
    rust_varint = None
    coq_witness = None
    rust_witness = None
    coq_sighash = None
    rust_sighash = None
    try:
        with open("formal/coq/extraction/coq_varint_refinement.json", "r") as f:
            coq_varint = json.load(f)
        with open("rust_varint_refinement.json", "r") as f:
            rust_varint = json.load(f)
    except FileNotFoundError:
        pass
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in varint refinement summary: {e}")
        sys.exit(1)

    try:
        with open("formal/coq/extraction/coq_witness_refinement.json", "r") as f:
            coq_witness = json.load(f)
        with open("rust_witness_refinement.json", "r") as f:
            rust_witness = json.load(f)
    except FileNotFoundError:
        pass
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in witness refinement summary: {e}")
        sys.exit(1)

    try:
        with open("formal/coq/extraction/coq_sighash_refinement.json", "r") as f:
            coq_sighash = json.load(f)
        with open("rust_sighash_refinement.json", "r") as f:
            rust_sighash = json.load(f)
    except FileNotFoundError:
        pass
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in sighash refinement summary: {e}")
        sys.exit(1)

    print(f"Coq vectors: {len(coq_data)} test cases")
    print(f"Rust vectors: {len(rust_data)} test cases")
    print()

    # Build lookup by name
    coq_by_name = {v["name"]: v for v in coq_data}
    rust_by_name = {v["name"]: v for v in rust_data}

    mismatches = []
    missing = []
    unexpected = []

    for name in coq_by_name:
        if name not in rust_by_name:
            missing.append(f"Rust missing: {name}")
            continue

        coq_vec = coq_by_name[name]
        rust_vec = rust_by_name[name]

        # Compare pk_len
        if coq_vec["pk_len"] != rust_vec["pk_len"]:
            mismatches.append(
                f"{name}: pk_len mismatch - Coq:{coq_vec['pk_len']} vs Rust:{rust_vec['pk_len']}"
            )

        # Compare sig_len
        if coq_vec["sig_len"] != rust_vec["sig_len"]:
            mismatches.append(
                f"{name}: sig_len mismatch - Coq:{coq_vec['sig_len']} vs Rust:{rust_vec['sig_len']}"
            )

        # Compare witness (the critical check)
        if coq_vec["witness"] != rust_vec["witness"]:
            mismatches.append(f"{name}: WITNESS MISMATCH")
            mismatches.append(f"  Coq:  {coq_vec['witness'][:60]}...")
            mismatches.append(f"  Rust: {rust_vec['witness'][:60]}...")

    for name in rust_by_name:
        if name not in coq_by_name:
            unexpected.append(f"Unexpected Rust vector: {name}")

    if missing:
        print("=== MISSING VECTORS ===")
        for m in missing:
            print(m)
        print()

    if unexpected:
        print("=== UNEXPECTED VECTORS ===")
        for u in unexpected:
            print(u)
        print()

    if mismatches or missing or unexpected:
        print("=== MISMATCHES FOUND ===")
        for m in mismatches:
            print(m)
        print()
        sys.exit(1)

    if coq_varint is not None or rust_varint is not None:
        if coq_varint != rust_varint:
            print("=== VARINT REFINEMENT MISMATCH ===")
            print(f"Coq:  {coq_varint}")
            print(f"Rust: {rust_varint}")
            print()
            sys.exit(1)
        print("Exhaustive u16 varint refinement summaries match!")

    if coq_witness is not None or rust_witness is not None:
        if coq_witness != rust_witness:
            print("=== WITNESS REFINEMENT MISMATCH ===")
            print(f"Coq:  {coq_witness}")
            print(f"Rust: {rust_witness}")
            print()
            sys.exit(1)
        print("Witness parser/serializer/consensus-domain/trace refinement summaries match!")

    if coq_sighash is not None or rust_sighash is not None:
        if coq_sighash != rust_sighash:
            print("=== SIGHASH TRANSCRIPT REFINEMENT MISMATCH ===")
            print(f"Coq:  {coq_sighash}")
            print(f"Rust: {rust_sighash}")
            print()
            sys.exit(1)
        print("Sighash transcript refinement summaries match!")

    print("=== SUCCESS ===")
    print("All bounded vectors match byte-for-byte!")
    if coq_witness is not None:
        print("PO-8: bounded Coq witness model ↔ Rust encoding implementation extraction-boundary evidence")
        print("      Run ./verify_source_refinement.sh for Kani source-level bounded refinement")
        print("      Run ./verify_compiled_refinement.sh for release-binary translation validation")
    else:
        print("PO-8: bounded Coq canonical serializer ↔ Rust baseline-vector evidence")
        print("      Full extraction run adds exhaustive u16 varint, consensus-domain, and witness trace refinement")
        print("      Source-level bounded parser refinement is verified by ./verify_source_refinement.sh")
        print("      Release-binary refinement validation is verified by ./verify_compiled_refinement.sh")
    if coq_sighash is not None:
        print("PO-4: Coq sighash transcript model ↔ Rust preimage serialization evidence")
        print("      Run ./verify_sighash_refinement.sh for release-binary transcript validation")
    print()
    print("Proof Obligations Status:")
    print("  PO-1 (Totality):          VERIFIED")
    print("  PO-2 (Determinism):       VERIFIED")
    print("  PO-3 (Parse Canonicality): VERIFIED")
    print("  PO-4 (Sighash Commitment): VERIFIED MODEL (SighashV2.v + Rust PBT)")
    if coq_sighash is not None:
        print("  PO-4 (Rust transcript):    COQ-EXTRACTED VS RUST PREIMAGE SERIALIZATION REFINEMENT")
        print("  PO-4 (Compiled artifact):  RUN ./verify_sighash_refinement.sh FOR RELEASE-BINARY TRANSCRIPT VALIDATION")
    print("  PO-5 (Transition Det.):    VERIFIED")
    print("  PO-7 (Cost Boundedness):   VERIFIED")
    if coq_witness is not None:
        print("  PO-8 (Correspondence):     BOUNDED EXTRACTION EVIDENCE + CONCRETE CANONICALITY + EXHAUSTIVE VARINT + CONSENSUS WITNESS REFINEMENT (<= u16)")
        print("  PO-8 (Rust source):        RUN ./verify_source_refinement.sh FOR KANI SOURCE-LEVEL BOUNDED REFINEMENT")
        print("  PO-8 (Compiled artifact):  RUN ./verify_compiled_refinement.sh FOR RELEASE-BINARY TRANSLATION VALIDATION")
    elif coq_varint is not None:
        print("  PO-8 (Correspondence):     BOUNDED EVIDENCE + CONCRETE CANONICALITY + EXHAUSTIVE VARINT REFINEMENT (<= u16)")
    else:
        print("  PO-8 (Correspondence):     BASELINE GOLDEN VECTORS ONLY; RUN build_extraction.sh FOR FULL REFINEMENT")


if __name__ == "__main__":
    main()
